---
- name: Check if Collectd is already installed.
  stat:
    path: "{{ collectd_bin_path }}"
  register: collectd_bin

- name: Get SignalFx's collectd installer.
  get_url:
    url: "{{ collectd_installer_url }}"
    dest: /tmp/collectd-install
    mode: 0754
  when: collectd_bin.stat.exists != True

- name: Run the collectd installer using the provided token.
  command: "{{ collectd_install_command }}"
  when:
    - collectd_bin.stat.exists != True
    - collectd_role_test_mode != True

- name: Ensure configured integration configurations are added.
  get_url:
    url: "{{ item.url }}"
    dest: "/etc/collectd/managed_config/{{ item.filename }}"
    mode: 0644
  with_items: "{{ collectd_signalfx_managed_config }}"
  notify: restart collectd

- name: Change managed configurations if needed.
  lineinfile:
    dest: "/etc/collectd/managed_config/{{ item.filename }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ collectd_managed_config_changes }}"
  notify: restart collectd
