---
- name: Check if Collectd is already installed.
  stat:
    path: "{{ collectd_bin_path }}"
  register: collectd_bin

- name: Get SignalFx's collectd installer.
  get_url:
    url: "{{ collectd_installer_url }}"
    dest: /tmp/collectd-install
    mode: 0754
  when: not collectd_bin.stat.exists

- name: Run the collectd installer using the provided token.
  command: "{{ collectd_install_command }}"
  when:
    - not collectd_bin.stat.exists
    - not collectd_role_test_mode

- name: Set collectd hostname (if configured).
  lineinfile:
    dest: /etc/collectd/collectd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "{{ item.insertbefore | default('') }}"
  with_items:
    - regexp: "^FQDNLookup .+$"
      line: "FQDNLookup false"
    - regexp: "^Hostname .+$"
      line: 'Hostname "{{ collectd_hostname }}"'
      insertbefore: "^FQDNLookup.+$"
  when: collectd_hostname
  notify: restart collectd

- name: Ensure configured integration configurations are added.
  get_url:
    url: "{{ item.url }}"
    dest: "/etc/collectd/managed_config/{{ item.filename }}"
    mode: 0644
  with_items: "{{ collectd_signalfx_managed_config }}"
  notify: restart collectd

- name: Change managed configurations if needed.
  lineinfile:
    dest: "/etc/collectd/managed_config/{{ item.filename }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ collectd_managed_config_changes }}"
  notify: restart collectd

- name: Ensure SignalFx token is current.
  lineinfile:
    dest: "/etc/collectd/managed_config/{{ item.file }}"
    regexp: '^.+{{ item.variable }} ".+"$'
    line: '    {{ item.variable }} "{{ signalfx_token }}"'
    state: present
  notify: restart collectd
  with_items:
    - file: 10-signalfx.conf
      variable: 'Token'
    - file: 10-write_http-plugin.conf
      variable: 'Password'
  when: not collectd_role_test_mode
